// Quiz difficulty level.
export type Difficulty = "easy" | "medium" | "hard";

// Processing state of an uploaded material.
export type MaterialStatus = "processing" | "ready" | "error";

// A topic extracted from a material by the AI layer.
export interface Topic {
  id: string;
  name: string;
  summary: string;
  keyPoints: string[];
}

// One headed body section inside generated study notes.
export interface NoteSection {
  heading: string;
  content: string;
}

// One question-and-answer pair from a generated flashcard set.
export interface Flashcard {
  front: string;
  back: string;
}

// The full study-notes payload the generateNotes AI job returns and a
// material caches: title, 4 to 8 sections, a summary, key points and
// flashcards, all written only from the material's own text.
export interface MaterialNotes {
  title: string;
  sections: NoteSection[];
  summary: string;
  keyPoints: string[];
  flashcards: Flashcard[];
}

// One stored chat turn, either from the student or from the tutor.
export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

// An uploaded piece of lecture material and what was learned from it.
export interface Material {
  id: string;
  profileId: string;
  title: string;
  sourceName: string;
  pageCount: number;
  charCount: number;
  status: MaterialStatus;
  topics: Topic[];
  createdAt: string;
  // Study notes generated by /api/notes and cached here until a refresh
  // asks for them again. Absent until the first /api/notes call for this
  // material, so existing materials stay valid without a data migration.
  notes?: MaterialNotes | null;
}

// One ordered slice of a material's extracted text, stored for later AI passes.
export interface Chunk {
  order: number;
  text: string;
}

// A single quiz question with its answer key, as stored server side.
export interface Question {
  qid: string;
  topicId: string;
  stem: string;
  options: [string, string, string, string];
  answerIndex: 0 | 1 | 2 | 3;
  explanation: string;
}

// The client-safe view of a Question. Since the UI port, quiz responses also
// carry the answer key (the answer index renamed to correctAnswerIndex, plus
// the explanation) so the Quiz screen can reveal it client-side; grading in
// /api/attempt stays server-side and authoritative.
// Both fields are required: every producer must set them.
export type PublicQuestion = Omit<Question, "answerIndex" | "explanation"> & {
  correctAnswerIndex: 0 | 1 | 2 | 3;
  explanation: string;
};

// A generated quiz covering one or more topics of a material.
export interface Quiz {
  id: string;
  profileId: string;
  materialId: string;
  topicIds: string[];
  difficulty: Difficulty;
  questions: Question[];
  createdAt: string;
}

// The learner's choice for one quiz question, plus whether it was correct.
export interface AttemptAnswer {
  qid: string;
  chosenIndex: number;
  correct: boolean;
}

// A completed run through a quiz.
export interface Attempt {
  id: string;
  profileId: string;
  quizId: string;
  materialId: string;
  answers: AttemptAnswer[];
  score: number;
  completedAt: string;
}

// A profile's running mastery record for one topic, across all attempts.
export interface TopicProgress {
  topicId: string;
  materialId: string;
  name: string;
  attempts: number;
  correct: number;
  wrong: number;
  mastery: number;
  lastAttemptAt: string | null;
  weak: boolean;
  explanation: string | null;
  explanationAt: string | null;
}

// The anonymous, browser-held identity that owns materials, quizzes and progress.
export interface Profile {
  id: string;
  createdAt: string;
  lastSeenAt: string;
  latestFeedback: string | null;
  latestFeedbackAt: string | null;
  aiCallsToday: number;
  aiCallsDate: string;
}

// What backends the running app is actually wired to, for display and diagnostics.
export interface RuntimeStatus {
  ai: "gemini" | "mock";
  store: "firestore" | "memory";
  model: string | null;
}
